"""Added ArticlesCategory table

Revision ID: 08a30fcfa9ef
Revises: ab9c7c2e8b97
Create Date: 2024-09-10 10:58:17.386462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a30fcfa9ef'
down_revision: Union[str, None] = 'ab9c7c2e8b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
