"""Articles

Revision ID: 34f1adda6c33
Revises: e438b85a3cce
Create Date: 2024-09-10 12:09:45.750304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f1adda6c33'
down_revision: Union[str, None] = 'e438b85a3cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_category_id'), 'articles_category', ['id'], unique=False)
    op.add_column('articles', sa.Column('article_category_id', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('author', sa.String(), nullable=True))
    op.create_foreign_key(None, 'articles', 'articles_category', ['article_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'article_category_id')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles_category')
    op.drop_table('articles_category')
    # ### end Alembic commands ###
