"""All tables

Revision ID: 3555cc553ba4
Revises: ff80ba9907fd
Create Date: 2024-08-02 07:45:49.629210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '3555cc553ba4'
down_revision: Union[str, None] = 'ff80ba9907fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_id'), 'bank', ['id'], unique=False)
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(), nullable=False),
    sa.Column('currency_icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_table('daily_exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), default=func.now()),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_exchangerate_id'), 'daily_exchangerate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_exchangerate_id'), table_name='daily_exchangerate')
    op.drop_table('daily_exchangerate')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_bank_id'), table_name='bank')
    op.drop_table('bank')
    # ### end Alembic commands ###
