"""Readded ArticlesCategory table

Revision ID: 3bcf414457f9
Revises: 08a30fcfa9ef
Create Date: 2024-09-10 11:13:43.059932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcf414457f9'
down_revision: Union[str, None] = '08a30fcfa9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_category_id'), 'articles_category', ['id'], unique=False)
    op.create_foreign_key(None, 'articles', 'articles_category', ['article_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles_category')
    op.drop_table('articles_category')
    # ### end Alembic commands ###
