"""ArticleID added to the articles

Revision ID: ab9c7c2e8b97
Revises: fdc2ad04de7d
Create Date: 2024-09-06 20:15:54.451691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9c7c2e8b97'
down_revision: Union[str, None] = 'fdc2ad04de7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###
