"""Articles Category Added

Revision ID: fdc2ad04de7d
Revises: e438b85a3cce
Create Date: 2024-09-06 18:54:51.695307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc2ad04de7d'
down_revision: Union[str, None] = 'e438b85a3cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'articles_category', ['article_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'article_category_id')
    # ### end Alembic commands ###
